# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.28.0"
minimal_mistakes_skin: "dirt" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "catppuccin_latte", "catppuccin_mocha"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Site Settings
locale                   : "de-DE"
title                    : "Romirer Hendls"
title_separator          : ""
subtitle                 : "" # site tagline that appears below site title in masthead
name                     : "Romirer Hendls"
description              : "familiengeführter Grillbetrieb seit 1978!" # displayed in Feed.xml and Google Description
url                      : "https://romirer-hendl.at" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
brand_color              : "#ff0000" 
baseurl                  : "" # the subpath of your site it is also the github repo, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
enable_copy_code_button  : true #true, false (default)
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : true # true, false (default)
search                   : # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
lunr:
  search_within_pages    : # true, false (default)
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
timezone: Europe/Vienna  

# Site Footer
footer:
  links:
    - label: "Impressum"
      url: /impressum
      icon: "fa fa-gavel"
    - label: "Datenschutz"
      url: /privacy
      icon: "fa fa-lock"
  since: "2026"


# Defaults
defaults:
  - scope:
      path: ""
      type: splash
    values:
      toc_sticky: true
  - scope:
      path: ""
      type: single
    values:
      toc_sticky: true      

include:
  - _pages